name: Build and deploy container to Azure Container App - backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/projbezpieczenstwo/backend:latest

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Azure login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#      - name: Wait for previous provisioning to finish
#        run: |
#          APP=backend
#          RG=Projekt_Bezpieczeństwo
#          echo "Checking provisioningState..."
#          STATE=$(az containerapp show \
#            --name $APP \
#            --resource-group $RG \
#            --query properties.provisioningState -o tsv)
#          until [ "$STATE" = "Succeeded" ]; do
#            echo "  provisioningState is '$STATE'; waiting 15s..."
#            sleep 15
#            STATE=$(az containerapp show \
#              --name $APP \
#              --resource-group $RG \
#              --query properties.provisioningState -o tsv)
#          done
#          echo ":white_check_mark: provisioningState is Succeeded, safe to deploy."  # :contentReference[oaicite:0]{index=0}
#      - name: Deploy to Azure Container App
#        uses: azure/container-apps-deploy-action@v1
#        with:
#          resourceGroup: Projekt_Bezpieczeństwo
#          containerAppName: backend-app
#          imageToDeploy: ghcr.io/projbezpieczenstwo/backend:latest
