name: Merge from repos on dispatch

on:
  repository_dispatch:
    types: [fork-update]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CR_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add fork remote dynamically
        run: |
          FORK_OWNER=$(jq -r .fork <<< '${{ toJson(github.event.client_payload) }}')
          REPO_NAME=$(jq -r .repo <<< '${{ toJson(github.event.client_payload) }}')
          git remote add "${REPO_NAME}" https://github.com/${FORK_OWNER}/${REPO_NAME}.git
          git fetch "${REPO_NAME}" master || { echo "Failed to fetch main branch"; exit 1; }
          git merge --no-ff --allow-unrelated-histories "refs/remotes/${REPO_NAME}/master" -m "Auto-merge from ${FORK_OWNER}/${REPO_NAME}"

      - name: Push changes
        run: git push origin main
