name: Merge from repos on dispatch

on:
  repository_dispatch:
    types: [fork-update]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CR_PAT }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download fork repo into folder
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          FORK_OWNER=$(echo "$PAYLOAD" | jq -r .fork)
          REPO_NAME=$(echo "$PAYLOAD" | jq -r .repo)
          echo "Cloning ${FORK_OWNER}/${REPO_NAME} into ./${REPO_NAME}"
          mkdir "${REPO_NAME}"
          cd "${REPO_NAME}"
          git init
          git remote add origin "https://github.com/${FORK_OWNER}/${REPO_NAME}.git"
          git fetch --depth=1 origin master
          git archive origin/master | tar -x -C .
          rm -rf .git
          rm -rf .github

      - name: Push changes to main
        run: |
          git add .
          git commit -m "Added ${REPO_NAME} from fork"
          git push origin main
